spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  sum-queue: sumQueue
  subtract-queue: subtractQueue
  multiply-queue: multiplyQueue
  divide-queue: divideQueue
operator:
  sum-operator: sum
  subtract-operator: subtract
  multiply-operator: multiply
  divide-operator: divide
server:
  port: 8081
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([%X{requestId}]) %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %clr([%X{requestId}]) %m%n%wEx"